account_sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
auth_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

TWILIO = Twilio::REST::Client.new account_sid, auth_token

NUMBER_REGISTERED_WITH_TWILIO = '+12345678900'
NUMBER_TO_RECEIVE_NOTIFICATIONS_ON = '+12345678900'